<?php
/**
 * EdFiTribalAffiliationDescriptor
 *
 * PHP version 7.3
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 5.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace OpenAPI\Client\Model;

use \ArrayAccess;
use \OpenAPI\Client\ObjectSerializer;

/**
 * EdFiTribalAffiliationDescriptor Class Doc Comment
 *
 * @category Class
 * @package  OpenAPI\Client
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 * @implements \ArrayAccess<TKey, TValue>
 * @template TKey int|null
 * @template TValue mixed|null
 */
class EdFiTribalAffiliationDescriptor implements ModelInterface, ArrayAccess, \JsonSerializable
{
    public const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'edFi_tribalAffiliationDescriptor';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'id' => 'string',
        'tribal_affiliation_descriptor_id' => 'int',
        'code_value' => 'string',
        'description' => 'string',
        'effective_begin_date' => '\DateTime',
        'effective_end_date' => '\DateTime',
        'namespace' => 'string',
        'short_description' => 'string',
        '_etag' => 'string',
        '_last_modified_date' => '\DateTime'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      * @phpstan-var array<string, string|null>
      * @psalm-var array<string, string|null>
      */
    protected static $openAPIFormats = [
        'id' => null,
        'tribal_affiliation_descriptor_id' => 'int32',
        'code_value' => null,
        'description' => null,
        'effective_begin_date' => 'date',
        'effective_end_date' => 'date',
        'namespace' => null,
        'short_description' => null,
        '_etag' => null,
        '_last_modified_date' => 'date-time'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'id' => 'id',
        'tribal_affiliation_descriptor_id' => 'tribalAffiliationDescriptorId',
        'code_value' => 'codeValue',
        'description' => 'description',
        'effective_begin_date' => 'effectiveBeginDate',
        'effective_end_date' => 'effectiveEndDate',
        'namespace' => 'namespace',
        'short_description' => 'shortDescription',
        '_etag' => '_etag',
        '_last_modified_date' => '_lastModifiedDate'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'id' => 'setId',
        'tribal_affiliation_descriptor_id' => 'setTribalAffiliationDescriptorId',
        'code_value' => 'setCodeValue',
        'description' => 'setDescription',
        'effective_begin_date' => 'setEffectiveBeginDate',
        'effective_end_date' => 'setEffectiveEndDate',
        'namespace' => 'setNamespace',
        'short_description' => 'setShortDescription',
        '_etag' => 'setEtag',
        '_last_modified_date' => 'setLastModifiedDate'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'id' => 'getId',
        'tribal_affiliation_descriptor_id' => 'getTribalAffiliationDescriptorId',
        'code_value' => 'getCodeValue',
        'description' => 'getDescription',
        'effective_begin_date' => 'getEffectiveBeginDate',
        'effective_end_date' => 'getEffectiveEndDate',
        'namespace' => 'getNamespace',
        'short_description' => 'getShortDescription',
        '_etag' => 'getEtag',
        '_last_modified_date' => 'getLastModifiedDate'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }


    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['id'] = $data['id'] ?? null;
        $this->container['tribal_affiliation_descriptor_id'] = $data['tribal_affiliation_descriptor_id'] ?? null;
        $this->container['code_value'] = $data['code_value'] ?? null;
        $this->container['description'] = $data['description'] ?? null;
        $this->container['effective_begin_date'] = $data['effective_begin_date'] ?? null;
        $this->container['effective_end_date'] = $data['effective_end_date'] ?? null;
        $this->container['namespace'] = $data['namespace'] ?? null;
        $this->container['short_description'] = $data['short_description'] ?? null;
        $this->container['_etag'] = $data['_etag'] ?? null;
        $this->container['_last_modified_date'] = $data['_last_modified_date'] ?? null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['code_value'] === null) {
            $invalidProperties[] = "'code_value' can't be null";
        }
        if ((mb_strlen($this->container['code_value']) > 50)) {
            $invalidProperties[] = "invalid value for 'code_value', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['description']) && (mb_strlen($this->container['description']) > 1024)) {
            $invalidProperties[] = "invalid value for 'description', the character length must be smaller than or equal to 1024.";
        }

        if ($this->container['namespace'] === null) {
            $invalidProperties[] = "'namespace' can't be null";
        }
        if ((mb_strlen($this->container['namespace']) > 255)) {
            $invalidProperties[] = "invalid value for 'namespace', the character length must be smaller than or equal to 255.";
        }

        if ($this->container['short_description'] === null) {
            $invalidProperties[] = "'short_description' can't be null";
        }
        if ((mb_strlen($this->container['short_description']) > 75)) {
            $invalidProperties[] = "invalid value for 'short_description', the character length must be smaller than or equal to 75.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return self
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }

    /**
     * Gets tribal_affiliation_descriptor_id
     *
     * @return int|null
     */
    public function getTribalAffiliationDescriptorId()
    {
        return $this->container['tribal_affiliation_descriptor_id'];
    }

    /**
     * Sets tribal_affiliation_descriptor_id
     *
     * @param int|null $tribal_affiliation_descriptor_id A unique identifier used as Primary Key, not derived from business logic, when acting as Foreign Key, references the parent table.
     *
     * @return self
     */
    public function setTribalAffiliationDescriptorId($tribal_affiliation_descriptor_id)
    {
        $this->container['tribal_affiliation_descriptor_id'] = $tribal_affiliation_descriptor_id;

        return $this;
    }

    /**
     * Gets code_value
     *
     * @return string
     */
    public function getCodeValue()
    {
        return $this->container['code_value'];
    }

    /**
     * Sets code_value
     *
     * @param string $code_value A code or abbreviation that is used to refer to the descriptor.
     *
     * @return self
     */
    public function setCodeValue($code_value)
    {
        if ((mb_strlen($code_value) > 50)) {
            throw new \InvalidArgumentException('invalid length for $code_value when calling EdFiTribalAffiliationDescriptor., must be smaller than or equal to 50.');
        }

        $this->container['code_value'] = $code_value;

        return $this;
    }

    /**
     * Gets description
     *
     * @return string|null
     */
    public function getDescription()
    {
        return $this->container['description'];
    }

    /**
     * Sets description
     *
     * @param string|null $description The description of the descriptor.
     *
     * @return self
     */
    public function setDescription($description)
    {
        if (!is_null($description) && (mb_strlen($description) > 1024)) {
            throw new \InvalidArgumentException('invalid length for $description when calling EdFiTribalAffiliationDescriptor., must be smaller than or equal to 1024.');
        }

        $this->container['description'] = $description;

        return $this;
    }

    /**
     * Gets effective_begin_date
     *
     * @return \DateTime|null
     */
    public function getEffectiveBeginDate()
    {
        return $this->container['effective_begin_date'];
    }

    /**
     * Sets effective_begin_date
     *
     * @param \DateTime|null $effective_begin_date The beginning date of the period when the descriptor is in effect. If omitted, the default is immediate effectiveness.
     *
     * @return self
     */
    public function setEffectiveBeginDate($effective_begin_date)
    {
        $this->container['effective_begin_date'] = $effective_begin_date;

        return $this;
    }

    /**
     * Gets effective_end_date
     *
     * @return \DateTime|null
     */
    public function getEffectiveEndDate()
    {
        return $this->container['effective_end_date'];
    }

    /**
     * Sets effective_end_date
     *
     * @param \DateTime|null $effective_end_date The end date of the period when the descriptor is in effect.
     *
     * @return self
     */
    public function setEffectiveEndDate($effective_end_date)
    {
        $this->container['effective_end_date'] = $effective_end_date;

        return $this;
    }

    /**
     * Gets namespace
     *
     * @return string
     */
    public function getNamespace()
    {
        return $this->container['namespace'];
    }

    /**
     * Sets namespace
     *
     * @param string $namespace A globally unique namespace that identifies this descriptor set. Author is strongly encouraged to use the Universal Resource Identifier (http, ftp, file, etc.) for the source of the descriptor definition. Best practice is for this source to be the descriptor file itself, so that it can be machine-readable and be fetched in real-time, if necessary.
     *
     * @return self
     */
    public function setNamespace($namespace)
    {
        if ((mb_strlen($namespace) > 255)) {
            throw new \InvalidArgumentException('invalid length for $namespace when calling EdFiTribalAffiliationDescriptor., must be smaller than or equal to 255.');
        }

        $this->container['namespace'] = $namespace;

        return $this;
    }

    /**
     * Gets short_description
     *
     * @return string
     */
    public function getShortDescription()
    {
        return $this->container['short_description'];
    }

    /**
     * Sets short_description
     *
     * @param string $short_description A shortened description for the descriptor.
     *
     * @return self
     */
    public function setShortDescription($short_description)
    {
        if ((mb_strlen($short_description) > 75)) {
            throw new \InvalidArgumentException('invalid length for $short_description when calling EdFiTribalAffiliationDescriptor., must be smaller than or equal to 75.');
        }

        $this->container['short_description'] = $short_description;

        return $this;
    }

    /**
     * Gets _etag
     *
     * @return string|null
     */
    public function getEtag()
    {
        return $this->container['_etag'];
    }

    /**
     * Sets _etag
     *
     * @param string|null $_etag A unique system-generated value that identifies the version of the resource.
     *
     * @return self
     */
    public function setEtag($_etag)
    {
        $this->container['_etag'] = $_etag;

        return $this;
    }

    /**
     * Gets _last_modified_date
     *
     * @return \DateTime|null
     */
    public function getLastModifiedDate()
    {
        return $this->container['_last_modified_date'];
    }

    /**
     * Sets _last_modified_date
     *
     * @param \DateTime|null $_last_modified_date The date and time the resource was last modified.
     *
     * @return self
     */
    public function setLastModifiedDate($_last_modified_date)
    {
        $this->container['_last_modified_date'] = $_last_modified_date;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed|null
     */
    public function offsetGet($offset)
    {
        return $this->container[$offset] ?? null;
    }

    /**
     * Sets value based on offset.
     *
     * @param int|null $offset Offset
     * @param mixed    $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Serializes the object to a value that can be serialized natively by json_encode().
     * @link https://www.php.net/manual/en/jsonserializable.jsonserialize.php
     *
     * @return mixed Returns data which can be serialized by json_encode(), which is a value
     * of any type other than a resource.
     */
    public function jsonSerialize()
    {
       return ObjectSerializer::sanitizeForSerialization($this);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


