<?php
/**
 * ProgramSponsorDescriptorsApiTest
 * PHP version 7.4
 *
 * @category Class
 * @package  Descriptors
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Ed-Fi Operational Data Store API
 *
 * The Ed-Fi ODS / API enables applications to read and write education data stored in an Ed-Fi ODS through a secure REST interface.  ***  > *Note: Consumers of ODS / API information should sanitize all data for display and storage. The ODS / API provides reasonable safeguards against cross-site scripting attacks and other malicious content, but the platform does not and cannot guarantee that the data it contains is free of all potentially harmful content.*  ***
 *
 * The version of the OpenAPI document: 3
 * Generated by: https://openapi-generator.tech
 * Generator version: 7.9.0
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the endpoint.
 */

namespace Descriptors\Test\Api;

use \Descriptors\Configuration;
use \Descriptors\ApiException;
use \Descriptors\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * ProgramSponsorDescriptorsApiTest Class Doc Comment
 *
 * @category Class
 * @package  Descriptors
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ProgramSponsorDescriptorsApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for deleteProgramSponsorDescriptorById
     *
     * Deletes an existing resource using the resource identifier..
     *
     */
    public function testDeleteProgramSponsorDescriptorById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for deletesProgramSponsorDescriptors
     *
     * Retrieves deleted resources based on change version..
     *
     */
    public function testDeletesProgramSponsorDescriptors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProgramSponsorDescriptors
     *
     * Retrieves specific resources using the resource's property values (using the \"Get\" pattern)..
     *
     */
    public function testGetProgramSponsorDescriptors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for getProgramSponsorDescriptorsById
     *
     * Retrieves a specific resource using the resource's identifier (using the \"Get By Id\" pattern)..
     *
     */
    public function testGetProgramSponsorDescriptorsById()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for keyChangesProgramSponsorDescriptors
     *
     * Retrieves resources key changes based on change version..
     *
     */
    public function testKeyChangesProgramSponsorDescriptors()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for postProgramSponsorDescriptor
     *
     * Creates or updates resources based on the natural key values of the supplied resource..
     *
     */
    public function testPostProgramSponsorDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }

    /**
     * Test case for putProgramSponsorDescriptor
     *
     * Updates a resource based on the resource identifier..
     *
     */
    public function testPutProgramSponsorDescriptor()
    {
        // TODO: implement
        self::markTestIncomplete('Not implemented');
    }
}
